language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install pylint sympy"
# command to run tests
script:
  - "if [ -f *.py ]; then nosetests *.py; fi"
notifications:
  email: false
